version: '3.3'

services:
  sql:
    image: "${DTRSQLURL}:${BRANCH}"
    ports:
      - mode: ingress
        target: 1433
    deploy:
      replicas: 1
      placement:
        constraints: [node.platform.os == windows]
    networks:
      - dockerdevops

networks:
  dockerdevops:
    driver: overlay